### ISSUE TITLE
Course page spacing

### ISSUE THREAD

**Issue by abdulkdawson** [mitodl/ocw-course-hugo-theme#12]
There are a few adjustments that need to be made on the course page interior pages. 
1. Can we decrease the width of the body text?

2. Can we expand this line to meet the edge of the body text container? 
3. The line that is attached to the hide course info tab when the course drawer is open should be visible when it's closed.

<img width="479" alt="Screen Shot 2020-11-24 at 11 10 42 AM" src="https://user-images.githubusercontent.com/49685474/100134690-95c96100-2e56-11eb-9736-34759ea64749.png">

### related issue

- mitodl/hugo-course-publisher#413 course info tab needs more space

**Comment by alicewriteswrongs** [comment]
@abdulkdawson do these changes capture what you're looking for here?

![Screenshot from 2020-12-02 10-51-14](https://user-images.githubusercontent.com/6207644/100896303-7bae0500-348c-11eb-831e-559b9266cdf4.png)
![Screenshot from 2020-12-02 10-51-08](https://user-images.githubusercontent.com/6207644/100896326-7fda2280-348c-11eb-8171-99f3b7086162.png)
![Screenshot from 2020-12-02 10-50-45](https://user-images.githubusercontent.com/6207644/100896327-8072b900-348c-11eb-8772-4a5e9a1f4ff8.png)

**Comment by abdulkdawson** [comment]
@pdpinch this issue was completed, but another issue arose from this one where the "Course Info" tab is too close to the dividing line.
