### ISSUE TITLE
Course page: Course Info tab needs more space

### ISSUE THREAD

**Issue by abdulkdawson** [mitodl/ocw-course-hugo-theme#13]
The Hide Course Info tab is far too close to the body text. We need to give both the tab and the text some space.

<img width="480" alt="Screen Shot 2020-11-24 at 11 04 53 AM" src="https://user-images.githubusercontent.com/49685474/100133996-7ed63f00-2e55-11eb-986c-2cabe942df97.png">

**Comment by abdulkdawson** [comment]
@pdpinch This has not been completed.

**Comment by gumaerc** [comment]
@aliceriot I see you assigned yourself to this a while back, do you mind if I grab it?  I've actually already integrated this change into a PR I'm working on.

**Comment by gumaerc** [comment]
side note @abdulkdawson , how does this look?

![image](https://user-images.githubusercontent.com/12089658/109048543-32450e80-76a5-11eb-8040-5e63b30316cc.png)

**Comment by abdulkdawson** [comment]
@gumaerc This looks great.
