### ISSUE TITLE
CSS issues with course info on mobile

### ISSUE THREAD

**Issue by noisecapella** [mitodl/ocw-course-hugo-theme#93]
### Screenshot or Screencast

![Screenshot from 2021-04-28 11-52-04](https://user-images.githubusercontent.com/863262/116434332-542f4e80-a818-11eb-8fed-c6a1c07102b1.png)

**Comment by pdpinch** [comment]
@gumaerc did you have a PR to fix this?

**Comment by gumaerc** [comment]
This is a duplicate of https://github.com/mitodl/ocw-course-hugo-theme/issues/86, and yes it will be fixed by https://github.com/mitodl/ocw-course-hugo-theme/pull/87

**Comment by pdpinch** [comment]
Fixed by #87
