### ISSUE TITLE
Search: update course card to expand/collapse topics and instructors

### ISSUE THREAD

**Issue by abdulkdawson** [mitodl/ocw-course-hugo-theme#96]
The course cards must be updated to accommodate a long list of topics. We have decided to add an expand and collapse to the topics section within the card allowing the user to view the full list of topics if they choose. In its collapsed state the card will only show a limited amount of topics and have a teaser of additional topics. 

The expand and collapse can be applied to the instructor's list as well if the list exceeds a single line. 

Here is a link to the InVision project showing the updated cards: 

[https://projects.invisionapp.com/d/main?origin=v7#/console/18609637/447781243/preview?scrollOffset=1525.5555419921875](https://projects.invisionapp.com/d/main?origin=v7#/console/18609637/447781243/preview?scrollOffset=1525.5555419921875)

**Comment by pdpinch** [comment]
This has been superseded by a redesign of the search result cards.
